// AUTO-GENERATED by scripts/fetch-bacdive.mjs from BacDive API v2.
// Gap-fill only: finalize.mjs merges these UNDER scripts/profiles.mjs, so any
// curated value always wins. Delete this file to drop the BacDive-sourced fills.
export const BACDIVE_PROFILES = {
  "Abiotrophia defectiva": {
    "aesculin": "Negative",
    "vp": "Negative",
    "indole": "Negative",
    "fermentation": [
      "Sucrose",
      "Glucose",
      "Maltose",
      "Lactose"
    ]
  },
  "Achromobacter xylosoxidans": {
    "aesculin": "Negative",
    "indole": "Negative",
    "vp": "Positive"
  },
  "Acinetobacter baumannii": {
    "haemolysis": "Gamma",
    "aesculin": "Negative",
    "indole": "Negative",
    "citrate": "Positive"
  },
  "Acinetobacter lwoffii": {
    "haemolysis": "Gamma",
    "aesculin": "Negative",
    "indole": "Negative",
    "vp": "Negative",
    "citrate": "Negative"
  },
  "Actinomyces israelii": {
    "aesculin": "Positive",
    "oxidase": "Positive",
    "pyr": "Negative",
    "indole": "Negative",
    "vp": "Negative",
    "citrate": "Negative",
    "fermentation": [
      "Glucose",
      "Maltose",
      "Sucrose",
      "Lactose",
      "Mannitol"
    ]
  },
  "Actinomyces naeslundii": {
    "aesculin": "Positive",
    "oxidase": "Negative",
    "pyr": "Negative",
    "vp": "Negative",
    "indole": "Negative",
    "citrate": "Negative"
  },
  "Aerococcus urinae": {
    "vp": "Negative",
    "indole": "Negative",
    "fermentation": [
      "Glucose",
      "Mannitol",
      "Sucrose",
      "Maltose"
    ]
  },
  "Aeromonas caviae": {
    "vp": "Negative",
    "citrate": "Negative"
  },
  "Aeromonas hydrophila": {
    "aesculin": "Positive",
    "vp": "Positive",
    "citrate": "Negative"
  },
  "Aggregatibacter actinomycetemcomitans": {
    "haemolysis": "Gamma",
    "aesculin": "Negative",
    "pyr": "Negative",
    "vp": "Negative",
    "indole": "Negative"
  },
  "Aggregatibacter aphrophilus": {
    "aesculin": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "vp": "Negative"
  },
  "Arcobacter butzleri": {
    "pyr": "Negative",
    "aesculin": "Negative",
    "indole": "Negative",
    "citrate": "Negative"
  },
  "Bacillus cereus": {
    "aesculin": "Positive",
    "pyr": "Positive",
    "indole": "Negative",
    "vp": "Positive",
    "citrate": "Negative"
  },
  "Bacillus subtilis": {
    "indole": "Negative"
  },
  "Bacillus thuringiensis": {
    "aesculin": "Positive",
    "pyr": "Positive",
    "indole": "Negative"
  },
  "Bacteroides fragilis": {
    "haemolysis": "Alpha",
    "oxidase": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "fermentation": [
      "Maltose",
      "Sucrose",
      "Lactose",
      "Glucose"
    ]
  },
  "Bacteroides thetaiotaomicron": {
    "pyr": "Negative",
    "oxidase": "Negative"
  },
  "Bartonella bacilliformis": {
    "aesculin": "Negative",
    "urease": "Negative",
    "indole": "Negative",
    "fermentation": [
      "Sucrose",
      "Maltose",
      "Glucose"
    ]
  },
  "Bartonella henselae": {
    "haemolysis": "Gamma",
    "aesculin": "Negative",
    "urease": "Negative",
    "indole": "Negative"
  },
  "Bartonella quintana": {
    "aesculin": "Negative",
    "urease": "Negative",
    "indole": "Negative"
  },
  "Bordetella bronchiseptica": {
    "aesculin": "Negative",
    "indole": "Negative"
  },
  "Bordetella parapertussis": {
    "pyr": "Negative",
    "aesculin": "Negative",
    "indole": "Negative",
    "vp": "Negative",
    "citrate": "Negative"
  },
  "Bordetella pertussis": {
    "haemolysis": "Alpha",
    "aesculin": "Negative",
    "indole": "Negative",
    "citrate": "Negative"
  },
  "Brachyspira pilosicoli": {
    "pyr": "Negative",
    "aesculin": "Negative",
    "urease": "Negative",
    "indole": "Negative"
  },
  "Brucella abortus": {
    "haemolysis": "Gamma",
    "pyr": "Negative",
    "aesculin": "Negative",
    "vp": "Negative",
    "indole": "Negative"
  },
  "Brucella melitensis": {
    "haemolysis": "Gamma",
    "pyr": "Negative",
    "aesculin": "Negative",
    "vp": "Negative",
    "indole": "Negative"
  },
  "Brucella suis": {
    "haemolysis": "Gamma",
    "pyr": "Negative",
    "aesculin": "Negative",
    "vp": "Negative",
    "indole": "Negative"
  },
  "Burkholderia cepacia": {
    "haemolysis": "Gamma",
    "aesculin": "Negative",
    "indole": "Negative",
    "fermentation": [
      "Glucose"
    ]
  },
  "Burkholderia pseudomallei": {
    "aesculin": "Negative",
    "indole": "Negative"
  },
  "Campylobacter coli": {
    "aesculin": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "citrate": "Negative"
  },
  "Campylobacter fetus": {
    "haemolysis": "Gamma",
    "aesculin": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "citrate": "Negative"
  },
  "Campylobacter jejuni": {
    "aesculin": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "citrate": "Negative"
  },
  "Capnocytophaga canimorsus": {
    "aesculin": "Negative",
    "urease": "Negative",
    "indole": "Negative",
    "citrate": "Negative"
  },
  "Cardiobacterium hominis": {
    "aesculin": "Negative"
  },
  "Citrobacter freundii": {
    "aesculin": "Negative"
  },
  "Citrobacter koseri": {
    "aesculin": "Positive"
  },
  "Clostridioides difficile": {
    "haemolysis": "Gamma",
    "aesculin": "Negative",
    "pyr": "Negative",
    "indole": "Negative"
  },
  "Clostridium botulinum": {
    "aesculin": "Negative",
    "pyr": "Negative",
    "indole": "Negative"
  },
  "Clostridium perfringens": {
    "pyr": "Positive",
    "aesculin": "Negative",
    "indole": "Negative"
  },
  "Clostridium septicum": {
    "aesculin": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "vp": "Negative"
  },
  "Clostridium tetani": {
    "pyr": "Negative",
    "aesculin": "Negative",
    "indole": "Negative"
  },
  "Corynebacterium diphtheriae": {
    "aesculin": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "citrate": "Negative"
  },
  "Corynebacterium jeikeium": {
    "aesculin": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "citrate": "Negative",
    "fermentation": [
      "Glucose",
      "Maltose",
      "Sucrose"
    ]
  },
  "Corynebacterium ulcerans": {
    "aesculin": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "citrate": "Negative"
  },
  "Cronobacter sakazakii": {
    "aesculin": "Positive"
  },
  "Cutibacterium acnes": {
    "haemolysis": "Beta",
    "pyr": "Positive",
    "aesculin": "Negative",
    "oxidase": "Negative",
    "vp": "Negative",
    "fermentation": [
      "Glucose",
      "Mannitol",
      "Maltose"
    ]
  },
  "Edwardsiella tarda": {
    "aesculin": "Negative"
  },
  "Eikenella corrodens": {
    "aesculin": "Negative",
    "indole": "Negative",
    "fermentation": [
      "Glucose",
      "Sucrose",
      "Lactose",
      "Maltose"
    ]
  },
  "Elizabethkingia meningoseptica": {
    "citrate": "Negative",
    "fermentation": [
      "Maltose",
      "Glucose",
      "Mannitol",
      "Lactose"
    ]
  },
  "Enterobacter cloacae": {
    "aesculin": "Positive"
  },
  "Enterobacter hormaechei": {
    "aesculin": "Positive"
  },
  "Enterococcus faecalis": {
    "vp": "Positive",
    "indole": "Negative"
  },
  "Enterococcus faecium": {
    "vp": "Positive",
    "indole": "Negative"
  },
  "Enterococcus gallinarum": {
    "vp": "Positive",
    "indole": "Negative"
  },
  "Escherichia albertii": {
    "aesculin": "Negative"
  },
  "Escherichia coli": {
    "aesculin": "Negative"
  },
  "Escherichia fergusonii": {
    "aesculin": "Negative"
  },
  "Finegoldia magna": {
    "pyr": "Positive",
    "aesculin": "Negative",
    "vp": "Negative"
  },
  "Fusobacterium necrophorum": {
    "pyr": "Negative"
  },
  "Fusobacterium nucleatum": {
    "pyr": "Negative",
    "aesculin": "Negative",
    "oxidase": "Negative",
    "vp": "Negative",
    "fermentation": [
      "Glucose"
    ]
  },
  "Gardnerella vaginalis": {
    "aesculin": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "vp": "Negative",
    "citrate": "Negative"
  },
  "Granulicatella adiacens": {
    "aesculin": "Negative",
    "indole": "Negative",
    "vp": "Negative",
    "fermentation": [
      "Maltose",
      "Glucose",
      "Sucrose",
      "Mannitol"
    ]
  },
  "Haemophilus ducreyi": {
    "aesculin": "Negative",
    "indole": "Negative",
    "vp": "Negative",
    "citrate": "Negative",
    "fermentation": [
      "Glucose",
      "Maltose"
    ]
  },
  "Haemophilus influenzae": {
    "aesculin": "Negative",
    "indole": "Positive"
  },
  "Haemophilus parainfluenzae": {
    "aesculin": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "vp": "Negative"
  },
  "Hafnia alvei": {
    "aesculin": "Negative",
    "citrate": "Negative"
  },
  "Helicobacter cinaedi": {
    "aesculin": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "citrate": "Negative"
  },
  "Helicobacter pylori": {
    "aesculin": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "citrate": "Negative"
  },
  "Kingella kingae": {
    "aesculin": "Negative",
    "indole": "Negative"
  },
  "Klebsiella aerogenes": {
    "aesculin": "Positive",
    "urease": "Negative"
  },
  "Klebsiella oxytoca": {
    "aesculin": "Positive"
  },
  "Klebsiella pneumoniae": {
    "aesculin": "Positive"
  },
  "Legionella longbeachae": {
    "aesculin": "Negative",
    "indole": "Negative"
  },
  "Legionella pneumophila": {
    "aesculin": "Negative",
    "indole": "Negative",
    "citrate": "Positive",
    "fermentation": [
      "Glucose",
      "Maltose",
      "Mannitol"
    ]
  },
  "Leptotrichia buccalis": {
    "aesculin": "Positive",
    "oxidase": "Negative",
    "urease": "Negative",
    "pyr": "Negative",
    "vp": "Negative"
  },
  "Listeria ivanovii": {
    "pyr": "Negative",
    "indole": "Negative",
    "vp": "Positive"
  },
  "Listeria monocytogenes": {
    "pyr": "Negative",
    "indole": "Negative",
    "vp": "Positive"
  },
  "Micrococcus luteus": {
    "aesculin": "Negative",
    "coagulase": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "vp": "Positive",
    "citrate": "Negative"
  },
  "Moraxella catarrhalis": {
    "haemolysis": "Gamma",
    "aesculin": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "vp": "Negative"
  },
  "Morganella morganii": {
    "aesculin": "Negative"
  },
  "Mycobacterium abscessus": {
    "aesculin": "Positive",
    "pyr": "Positive",
    "oxidase": "Negative",
    "indole": "Negative"
  },
  "Mycobacterium avium": {
    "aesculin": "Negative",
    "oxidase": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "citrate": "Positive"
  },
  "Mycoplasma hominis": {
    "aesculin": "Negative",
    "pyr": "Negative",
    "vp": "Negative",
    "indole": "Negative"
  },
  "Neisseria gonorrhoeae": {
    "aesculin": "Negative",
    "indole": "Negative",
    "vp": "Negative",
    "citrate": "Negative"
  },
  "Neisseria lactamica": {
    "haemolysis": "Gamma",
    "aesculin": "Negative",
    "indole": "Negative"
  },
  "Neisseria meningitidis": {
    "aesculin": "Negative",
    "indole": "Negative"
  },
  "Nocardia asteroides": {
    "aesculin": "Positive",
    "oxidase": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "citrate": "Negative"
  },
  "Nocardia brasiliensis": {
    "aesculin": "Positive",
    "pyr": "Positive",
    "oxidase": "Negative",
    "indole": "Negative",
    "vp": "Negative",
    "citrate": "Positive"
  },
  "Pasteurella multocida": {
    "aesculin": "Negative",
    "pyr": "Negative",
    "vp": "Negative",
    "citrate": "Negative"
  },
  "Porphyromonas gingivalis": {
    "pyr": "Positive"
  },
  "Prevotella intermedia": {
    "pyr": "Negative",
    "fermentation": [
      "Maltose",
      "Sucrose",
      "Glucose"
    ]
  },
  "Prevotella melaninogenica": {
    "aesculin": "Negative",
    "oxidase": "Negative",
    "pyr": "Negative",
    "fermentation": [
      "Maltose",
      "Sucrose",
      "Lactose",
      "Glucose"
    ]
  },
  "Proteus mirabilis": {
    "aesculin": "Negative"
  },
  "Proteus vulgaris": {
    "aesculin": "Positive",
    "citrate": "Negative"
  },
  "Providencia rettgeri": {
    "aesculin": "Positive",
    "vp": "Negative"
  },
  "Providencia stuartii": {
    "aesculin": "Negative",
    "vp": "Negative"
  },
  "Pseudomonas aeruginosa": {
    "aesculin": "Negative",
    "indole": "Negative",
    "vp": "Negative"
  },
  "Pseudomonas fluorescens": {
    "aesculin": "Negative",
    "indole": "Negative"
  },
  "Pseudomonas putida": {
    "aesculin": "Negative",
    "indole": "Negative",
    "vp": "Negative"
  },
  "Rhodococcus hoagii": {
    "aesculin": "Positive",
    "pyr": "Negative",
    "vp": "Negative",
    "indole": "Negative",
    "citrate": "Negative"
  },
  "Salmonella enterica": {
    "aesculin": "Negative"
  },
  "Serratia marcescens": {
    "aesculin": "Positive"
  },
  "Shigella boydii": {
    "aesculin": "Negative"
  },
  "Shigella dysenteriae": {
    "aesculin": "Negative"
  },
  "Shigella flexneri": {
    "aesculin": "Negative"
  },
  "Shigella sonnei": {
    "aesculin": "Negative"
  },
  "Staphylococcus aureus": {
    "aesculin": "Negative"
  },
  "Staphylococcus epidermidis": {
    "aesculin": "Negative",
    "pyr": "Positive",
    "indole": "Negative",
    "vp": "Positive"
  },
  "Staphylococcus haemolyticus": {
    "aesculin": "Negative",
    "pyr": "Positive",
    "vp": "Positive",
    "indole": "Negative"
  },
  "Staphylococcus saprophyticus": {
    "pyr": "Negative",
    "aesculin": "Negative",
    "vp": "Positive",
    "indole": "Negative",
    "fermentation": [
      "Glucose",
      "Lactose",
      "Mannitol",
      "Sucrose",
      "Maltose"
    ]
  },
  "Stenotrophomonas maltophilia": {
    "haemolysis": "Beta",
    "aesculin": "Negative",
    "indole": "Negative",
    "vp": "Negative",
    "citrate": "Positive",
    "fermentation": [
      "Maltose",
      "Lactose"
    ]
  },
  "Streptobacillus moniliformis": {
    "haemolysis": "Gamma",
    "aesculin": "Negative",
    "pyr": "Negative",
    "indole": "Negative",
    "vp": "Negative"
  },
  "Streptococcus agalactiae": {
    "aesculin": "Negative",
    "indole": "Negative",
    "vp": "Positive"
  },
  "Streptococcus mutans": {
    "aesculin": "Positive",
    "pyr": "Negative",
    "vp": "Positive",
    "indole": "Negative"
  },
  "Streptococcus pneumoniae": {
    "pyr": "Negative",
    "aesculin": "Negative",
    "vp": "Negative",
    "indole": "Negative"
  },
  "Streptococcus pyogenes": {
    "aesculin": "Negative",
    "vp": "Negative",
    "indole": "Negative"
  },
  "Tannerella forsythia": {
    "aesculin": "Positive",
    "oxidase": "Positive",
    "urease": "Negative"
  },
  "Veillonella parvula": {
    "haemolysis": "Gamma",
    "aesculin": "Negative",
    "pyr": "Positive",
    "vp": "Negative"
  },
  "Vibrio alginolyticus": {
    "aesculin": "Positive",
    "citrate": "Negative"
  },
  "Vibrio cholerae": {
    "aesculin": "Positive",
    "vp": "Negative",
    "citrate": "Positive"
  },
  "Vibrio parahaemolyticus": {
    "aesculin": "Positive",
    "vp": "Negative",
    "citrate": "Positive"
  },
  "Vibrio vulnificus": {
    "aesculin": "Positive",
    "vp": "Negative",
    "citrate": "Negative"
  },
  "Yersinia enterocolitica": {
    "aesculin": "Negative",
    "vp": "Negative",
    "citrate": "Negative",
    "fermentation": [
      "Mannitol",
      "Sucrose",
      "Maltose",
      "Glucose"
    ]
  },
  "Yersinia pseudotuberculosis": {
    "haemolysis": "Gamma",
    "aesculin": "Positive",
    "pyr": "Positive"
  }
};
